apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: worker
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: POSTGRES_DB
              value: solequat
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: this1pass
---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: 8082 # 8762
      targetPort: 8082